"""empty message

Revision ID: 50fda1dd6c0f
Revises: 48a360167e8d
Create Date: 2021-09-15 08:26:02.813127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fda1dd6c0f'
down_revision = '48a360167e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdg', 'date_of_review',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdg', 'date_of_review',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
